config/routes.rb
Rails.application.routes.draw do
  root to: 'places#index'

  resources :places do
    resources :entries, only: [:index, :new, :create]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :place
  belongs_to :user
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :entries
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def authenticate(password)
    BCrypt::Password.new(self.password) == password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  def current_user
    puts "------------------ code before every request ------------------"
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :require_login
  before_action :set_place

  def index
    @entries = @place.entries.where(user_id: session[:user_id])
  end

  def new
    @entry = @place.entries.new
  end

  def create
    @entry = @place.entries.new(entry_params)
    @entry.user_id = session[:user_id]
    if @entry.save
      flash[:notice] = "Entry added successfully."
      redirect_to place_path(@place)
    else
      render :new
    end
  end

  private

  def set_place
    @place = Place.find(params[:place_id])
  end

  def entry_params
    params.require(:entry).permit(:title, :description, :occurred_on)
  end

  def require_login
    unless session[:user_id]
      flash[:notice] = "You must be logged in to access this section"
      redirect_to login_path
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :require_login, only: [:new, :create]

  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
    @entries = @place.entries.where(user_id: session[:user_id])
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:notice] = "Place added successfully."
      redirect_to places_path
    else
      render :new
    end
  end

  private

  def place_params
    params.require(:place).permit(:name)
  end

  def require_login
    unless session[:user_id]
      flash[:notice] = "You must be logged in to access this section"
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Hello, #{@user.username}."
      redirect_to places_path
    else
      flash[:notice] = "Invalid email or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Goodbye."
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.password = BCrypt::Password.create(params[:user][:password])
    if @user.save
      flash[:notice] = "Thanks for signing up. Now login."
      redirect_to login_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/new.html.erb
<h1>New Entry for <%= @place.name %></h1>

<%= form_with model: [@place, @entry], local: true do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :occurred_on, class: 'form-label' %>
    <%= form.date_field :occurred_on, class: 'form-control' %>
  </div>
  <%= form.submit 'Save', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', place_entries_path(@place), class: 'btn btn-secondary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel Journal </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Travel Journal</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <% if session[:user_id] %>
            <% @current_user = User.find(session[:user_id]) %>
            <li class="nav-item">
              <span class="nav-link">Logged in as: <%= @current_user.username %></span>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', logout_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/users/new">Signup</a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container mt-3">
      <div>
        <%= flash[:notice] %>
      </div>
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script

app/views/places/index.html.erb
<h1>Places</h1>

<ul>
  <% for place in @places %>
    <li><a href="/places/<%= place["id"] %>"><%= place["name"] %></a></li>
  <% end %>
</ul>

<p>
  <a href="/places/new">New place</a>
</p>

app/views/places/new.html.erb
<h1>Add New Place</h1>

<%= form_with model: @place, local: true do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <%= form.submit 'Save', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', places_path, class: 'btn btn-secondary' %>
<% end %>

app/views/places/show.html.erb
<div class="container mt-3">
  <h1><%= @place.name %></h1>

  <h2>My Entries</h2>
  <div class="row">
    <% @entries.each_slice(3) do |entry_row| %>
      <% entry_row.each do |entry| %>
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-body">
              <h5 class="card-title"><%= entry.title %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= entry.occurred_on %></h6>
              <p class="card-text"><%= entry.description %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <p>
    <%= link_to 'New Entry', new_place_entry_path(@place), class: 'btn btn-primary' %>
  </p>

  <p>
    <%= link_to 'Back to All Places', places_path, class: 'btn btn-secondary' %>
  </p>
</div>

app/views/users/new.html.erb
<h1>New User Account</h1>
<%= form_with model: @user, local: true do |form| %>
  <div class="mb-3">
    <%= form.label :username, class: 'form-label' %>
    <%= form.text_field :username, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :email, class: 'form-label' %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :password, class: 'form-label' %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>
  <%= form.submit 'Signup', class: 'btn btn-primary' %>
<% end %>